export { default as Home } from './Home'
export { default as Search } from './Search'
export { default as BusinessProfile } from './BusinessProfile'
export { default as PartnerLogin } from './partner/Login'
export { default as PartnerRegister } from './partner/Register'
export { default as PartnerDashboard } from './partner/Dashboard'
export { default as PartnerServices } from './partner/Services'
export { default as PartnerServiceForm } from './partner/ServiceForm'
export { default as PartnerStaff } from './partner/Staff'
export { default as PartnerStaffForm } from './partner/StaffForm'
export { default as PartnerAppointments } from './partner/Appointments'
export { default as PartnerCustomers } from './partner/Customers'
export { default as PartnerSettings } from './partner/Settings'
export { default as BookAppointment } from './BookAppointment'

// Customer pages
export { default as CustomerLogin } from './customer/Login'
export { default as CustomerRegister } from './customer/Register'
export { default as CustomerDashboard } from './customer/Dashboard'
export { default as CustomerAppointments } from './customer/Appointments'
export { default as CustomerFavorites } from './customer/Favorites'
export { default as CustomerProfile } from './customer/Profile'
export { default as CustomerSearch } from './customer/Search'
